### ISSUE TITLE
SOF file missing

### ISSUE THREAD

**Issue by drakonia667** [UzixLS/zx-sizif-512-ext#1]
Hello, the Quartus programmer needs SOF file to program the Altera CPLD. Where i can find it?

**Comment by UzixLS** [comment]
For CPLD programming POF file is used, not SOF (which is used for volatile configuration of FPGA).
POF file you can obtain here: https://github.com/UzixLS/zx-sizif-512-ext/blob/master/out/cpld.pof

**Comment by drakonia667** [comment]
Oh, just downloaded it again and it seems to be ok. Thanks!
