### ISSUE TITLE
Ferrite beads x Fastrons

### ISSUE THREAD

**Issue by arleybls** [UzixLS/zx-sizif-512-ext#2]
The assembled board image shows what looks like ferrite beads instead of the listed part on the BOM for L1 and L2. Are those alternatives for the Fastrons. Why not list the alternatives as well? If that is not the case can you share the part used on the assembled board image?

**Comment by UzixLS** [comment]
For these circuits L1 and L2 values doesn't really matter.

**Comment by arleybls** [comment]
Oo..so you say I could just short them? Or put any ferrite bead value? :)

**Comment by arleybls** [comment]
is the current rating 1A or also diesnt maater? (can i just shot?)
